# Generated by Django 5.1.1 on 2024-10-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pro',
            new_name='products',
        ),
    ]
