# Generated by Django 5.1.1 on 2024-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_decs_products_decsr'),
    ]

    operations = [
        migrations.CreateModel(
            name='custmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
