# Generated by Django 5.1.1 on 2024-10-16 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=50)),
                ('usep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mymodel')),
            ],
        ),
    ]
