# Generated by Django 5.1.1 on 2024-10-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product_user',
        ),
    ]
