# Generated by Django 5.1.1 on 2024-10-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_publisher_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phn', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course_model')),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='pub',
        ),
        migrations.DeleteModel(
            name='custmor',
        ),
        migrations.DeleteModel(
            name='emp',
        ),
        migrations.RemoveField(
            model_name='product_user',
            name='usep',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='bookmodel',
        ),
        migrations.DeleteModel(
            name='publisher',
        ),
        migrations.DeleteModel(
            name='mymodel',
        ),
        migrations.DeleteModel(
            name='product_user',
        ),
    ]
