# Generated by Django 5.1.1 on 2024-10-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_organizer_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='course',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='course_model',
        ),
        migrations.DeleteModel(
            name='student_model',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='organizer',
        ),
    ]
